allowBuilds:
    sharp: true
    unrs-resolver: true
    better-sqlite3: true
    esbuild: true
    msw: false
    "@sentry/cli": true

minimumReleaseAgeExclude:
    - react-hook-form@7.79.0
    - better-sqlite3@12.10.1
    - trickfire-docs

# patchedDependencies:
#     trickfire-docs: patches/trickfire-docs.patch
