name: Deploy

on:
    push:
        branches: [main]
        paths-ignore:
            - docs/**
            - ./**.md

concurrency:
    group: deploy
    cancel-in-progress: false

jobs:
    deploy:
        name: Deploy
        runs-on: [self-hosted, tfserver]
        environment: production

        steps:
            - name: Pull latest changes
              working-directory: /home/trickfire/dashboard
              run: git fetch origin main && git reset --hard origin/main

            - name: Run deploy script
              working-directory: /home/trickfire/dashboard
              run: bash scripts/deploy.sh
